import { Payment } from "src/app/model/manage-booking/Payment/Payment";
import { Service } from "./../Service/Service";
import { RoomDetails } from "./../../RoomDetails/RoomDetails";
import { BedDetails } from "./../../BedDetails/BedDetails";
import { Customer } from "../../Customer/customer";
import { TaxDetails } from "../../TaxDetail/TaxDetails";

export class Booking {
    id: number;
    groupBooking: boolean;
    customerId: number;
    propertyReservationNumber: string;
    referenceNumber: string;
    firstName: string;
    lastName: string;
    email: string;
    mobile: string;
    fromDate: string;
    fromDateCal: Date;
    toDate: string;
    roomType: string;
    hsnCode: string;
    roomPrice: number;
    airportShuttlePrice: string;
    businessEmail: string;
    businessName: string;
    notes: string;
    externalBookingId: string;
    externalSite: string;
    commissionAmount: string;
    gstAmount: string;
    paymentSurcharge: string;
    generateInvoice:boolean;
    netAmount: string;
    airportService: string;
    accomodationType: string;
    roomId: number;
    propertyId: number;
    available: boolean;
    modeOfPayment: string;
    cardNumber: number;
    expMonth: number;
    expYear: number;
    cvv: number;
    currency: string;
    token: string;
    auditType: string;
    bookingAmount: number;
    payableAmount: number;
    roomName: string;
    services: Service[];
    totalServiceAmount: number;
    totalExpenseAmount: number;
    totalPaymentAmount: number;
    outstandingAmount: number;
    discountAmount: number;
    discountPercentage: number;
    totalAmount: number;
    bookingStatus: string;
    invoiceUrl: string;
    noOfRooms: number;
    noOfPersons: number;
    checkinTime: string;
    checkoutTime: string;
    extraPersonCharge: number;
    noOfExtraPerson: number;
    roomDetails: RoomDetails[];
    bedDetails: BedDetails[];
    taxDetails: TaxDetails[];
    paymentDtoList: Payment[];
    isWhatsApp: boolean;
    createdBy: string;
    createdDate: string;
    lastModifiedBy: string;
    lastModifiedDate: string;
    changeType: string;
    message: string;
    noOfNights: number;
    expectedNights: number;
    roomBooking: Boolean;
    roomRatePlanName: string;
    planCode: string;
    beforeTaxAmount: number;
    taxAmount: number;
    advanceAmount: number;
    paymentStatus: string;
    otaBooking: boolean;
    arrivingFrom: string;
    departingTo: string;
    purposeOfVisit: string;

    checkInDateStr: string;
    checkOutDateStr: string;
    roomNumbers: string;
    idDetails: string;
    dateChangeCheckOutBookingTime: string;
    counterName: string;
    counterNumber: string;
    operatorName: string;

    additionalGuests: Customer[];

    extraChildCharge: number;
    noOfChildren: number;
    noOfExtraChild: number;
    invoiceId: string;
    customerCompanyName: string;

    totalBeforeTaxAmount: number;
    totalPayableAmount: number;
    bookingId: number;
    includeService: boolean;
    isIncludeExpense: boolean;
    propertyInvoiceNumber: number;
    customerImageurl: string;
    todoNotes: string;
    todosId: number;
    guestPhotoUrl: string;
    //mydefined
    isToggle: boolean = false;

    fromTime: string;
    toTime: string;
    roomTariffPaid: number;
    roomTariffPending: number;
    serviceAmountPending: number;
    serviceAmountPaid: number;
    totalRoomTariffBeforeDiscount: number;
    roomTariffBeforeDiscount: number;
    totalBookingAmount: number;
    twentyFourHoursCheckOut: boolean;
    convenienceFee: number;
    bookingCommissionAmount: number;
    companyName: string;
    groupBookingId: number;
    tcsFee: number;
    tdsFee: number;
    checkoutPeriod: number;
    operatorNotes: string;
    checkinSequenceNumber: string;

    constructor() {}
}
