export const BusinessServiceList = [
  {
    title: 'Electrician/Sparky',
    image: 'assets/images/electrical.jpg',
    icon: 'fa-2x fa fa-bolt',
    sub: [
      'Access Control Systems',
      'Adding Outlets',
      'Agricultural Grow Lighting',
      'Aluminum Wiring Replacement',
      'Back-Up Power Generators for Home/Office',
      'Basement Wiring',
      'Bath Remodeling Services',
      'Ceiling Fan Installation',
      'Circuit Additions',
      'Commercial Electrical Evaluation Audit',
      'Commercial New Construction',
      'Computer / Phone / Cable TV wiring',
      'Design-Build Commercial Electrical Services',
      'Educational Facilities Electric Services',
      'Electric Meter Installation',
      'Emergency Electrical Repairs',
      'Exit Signs and Egress Lighting',
      'Facility Maintenance Electrical',
      'General Electric – Commercial',
      'General Electric – Residential',
      'Hospitality Electrical Services',
      'Hot Tub Wiring',
      'Industrial Electrical Services',
      'Infrared Panel Scanning',
      'Kitchen Remodeling Services',
      'L.E.D Lighting',
      'Light Fixture Installation – Residential',
      'Lighting Design and Installation for Commercial Spaces',
      'Lighting Maintenance',
      'Lightning Strikes',
      'Low-Voltage Electric Services',
      'Outdoor Lighting',
      'Oven, Stove and Range Wiring',
      'Property Maintenance',
      'Remodel Services',
      'Residential Electrical Evaluation',
      'Security Cameras -- CCTV',
      'Security Lighting',
      'Server Room Electrical',
      'Service Additions',
      'Service Upgrades',
      'Standby Uninterruptable Power Supply -- UPS',
      'Switch and Receptacle Repair',
      'Whole Home Surge Protect',
    ],
  },
  {
    title: 'Cleaning Service',
    image: 'assets/images/Broom-2.jpg',
    icon: 'fa-2x fa fa-paint-brush',
    sub: [
      'Bathroom Cleaning',
      'Room Cleaning',
      'Windows cleaning',
      'Washing services',
      'Carpet cleaning business',
      'Swimming pool cleaning',
      'Car washing',
      'Furniture Cleaning',
    ],
  },
  {
    title: 'Education/Tuition',
    image: 'assets/images/education.jpeg',
    icon: 'fa-2x fa fa-book',
    sub: [
      'We have to keep adding available resources which can be school subjects/language/dance/music etc',
      'Language - Japanese',
      'Language - Spanish',
      'Subject - Class 8 Mathematics',
      'Music - Keyboard',
    ],
  },
  {
    title: 'Plumbing Service',
    image: 'assets/images/plumber-main.jpg',
    icon: 'fa-2x fa fa-wrench',
    sub: [
      'Replacement of Old Plumbing Works',
      'Drain Cleaning Services',
      'Rerouting Plumbing Pipes',
      'Pipe Leak Repair and Unclogging',
      'Toilet Repair',
      'Fixture Repair, Replacement, and Installation',
      'Water Heater Maintenance and Installation',
      'Sewer Line Blockage Cleaning',
      'Emergency Plumbing',
      'Plumbing Maintenance and Inspection',
    ],
  },
  {
    title: 'Beauty & Therapy',
    image: 'assets/images/hair-salon-near-me.jpg',
    icon: 'fa-2x fa fa-cut',
    sub: [],
  },
  {
    title: 'Builder/Handyman',
    image: 'assets/images/home-fixing-handyman.jpg',
    icon: 'fa-2x fa fa-hand-grab-o',
    sub: [
      'Grocery',
      'Wine & spirits',
      'Medicine',
      'Laundry',
      'Fresh Vegetables & fruits',
      'Milk and diary products',
      'Fish and Meat',
      'Wine & spirits',
      'Medicine',
      'Appraising of property',
      'Barbecue pit maintenance',
      'Cabinet refacing',
      'Carpentry',
      'Ceiling repair',
      'Ceramic tile repair',
      'Cleaning',
      'Concrete work',
      'Countertops',
      'Crown moulding',
      'Curtain hanging',
      'Decks',
      'Door installation',
      'Door repair',
      'Dryer repair',
      'Dryer vent cleaning',
      'Dryer vent installation',
      'Drywall Installation',
      'Drywall repair',
      'Electrical wiring',
      'Energy Updates',
      'Fan installation',
      'Fence fixing',
      'Fireplace cleaning',
      'Flooring Installation and Repair',
      'Foundations',
      'Framing',
      'Garage door openers',
      'Garage doors',
      'General Maintenance',
      'Gutter Cleaning',
      'Gutter Repair',
      'Heating system tune-up',
      'Home inspections',
      'Home security systems',
      'Hot tubs and spas',
      'Insulation installation (batts)',
      'Insulation installation (blown-in)',
      'Lamp repairs',
      'Landscaping',
      'Lawn care',
      'Lock set adjustment',
      'Maid service',
      'Molding installation',
      'Moving',
      'Paint removal',
      'Painting',
      'Patio stone installation',
      'Pest control',
      'Plumbing repairs',
      'Porches',
      'Remodeling basements',
      'Remodeling bathrooms',
      'Remodeling kitchens',
      'Roofing',
      'Safety modifications',
      'Sealing driveways',
      'Senior Living Modifications',
      'Septic system repair',
      'Shelf installation',
      'Shelving',
      'Skylight installation',
      'Solar panels',
      'Soundproofing',
      'Sprinkler repair',
      'Sprinkler system installation',
      'Stain removal',
      'Staining furniture',
      'Stone work',
      'Storage area construction',
      'Storage area repair',
      'Swapping a toilet',
      'Tiling',
      'Tile and Grout Cleaning',
      'Re-Grouting',
      'Trash Removal',
      'Wall building',
      'Waste and junk removal',
      'Water purification',
      'Water softening',
      'Window cleaning',
      'Welding',
      'Window installation',
      'Window repair',
      'Window screens',
    ],
  },
  {
    title: 'Cafe & Restaurants',
    image: 'assets/images/dp-1.jpg',
    icon: 'fa-2x fa fa-glass',
    sub: [],
  },
  {
    title: 'Pet Services',
    image: 'assets/images/dog-being-groomed.jpg',
    icon: 'fa-2x fa fa-paw',
    sub: [],
  },
  {
    title: 'Deliveries',
    image: 'assets/images/Deliveries.jpg',
    icon: 'fa-2x fa fa-truck',
    sub: [],
  },
  {
    title: 'Takeaways',
    image: 'assets/images/Takeaways.jpg',
    icon: 'fa-2x fa fa-shopping-bag',
    sub: [],
  },
  {
    title: 'Health & Fitness',
    image: 'assets/images/Takeaways.jpg',
    icon: 'fa-2x fa fa-shopping-bag',
    sub: [],
  },
  {
    title: 'Sports & Fun',
    image: 'assets/images/Takeaways.jpg',
    icon: 'fa-2x fa fa-shopping-bag',
    sub: [],
  },
  {
    title: 'Accessories and Repair Service',
    image: 'assets/images/Takeaways.jpg',
    icon: 'fa-2x fa fa-shopping-bag',
    sub: [],
  },
  {
    title: 'Heating Solutions',
    image: 'assets/images/Takeaways.jpg',
    icon: 'fa-2x fa fa-shopping-bag',
    sub: [],
  },
];
